CC=g++
CFLAGS=-std=c++17

INCLUDECADMIUM=-I/home/eldrazi/CADMIUM/Cadmium-Simulation-Environment/cadmium/include
INCLUDEJSON=-I/home/eldrazi/CADMIUM/Cadmium-Simulation-Environment/cadmium/json/include

convertScenario: convertScenario.cpp
	$(CC) -g $(CFLAGS) $(INCLUDEJSON) convertScenario.cpp -o convertScenario
	
